Added feroxbuster and weevely tools.
Orange-Cyberdefense/arsenal pull request #75
Opened 2024-02-02 05:56 UTC by Fastiraz

I've only added the feroxbuster and weevely tools to the cheats.

Feroxbuster is a fast, modern, simple, recursive content discovery tool written in Rust.

Weevely is a stealth PHP web shell that simulate telnet-like connection. It is an essential tool for web application post exploitation, and can be used as stealth backdoor or as a web shell to manage legit web accounts, even free hosted ones.

< Happy hacking! />

2024-02-26 11:08 UTC, Guilhem7 commented
Hi @Fastiraz,
Thanks for your help !

We would like to suggest some changes before merging your commits.
For the commit about __feroxbuster__:
- Please do not use local path in the cheat: *./feroxbuster* --> *feroxbuster* 
- Reduce the number of cheats for the tool, those you think are useful. (For instance the option: *--threads 200* can be remove in my opinion)

Use args from user:
```bash
feroxbuster -u http://127.1 --burp
```
To
```bash
feroxbuster -u <url> --burp
```

Also for the commit about __weevely__:
 - Remove the help *weevely generate \<password\>*, as this command does nothing

Use default arguments if needed:
```
weevely generate <password> web-shell.php
```
To
```
weevely generate <password> <output_file|web_shell.php>
```
Thanks again

2024-02-26 15:27 UTC, Fastiraz commented
I just made the last commits following your instructions.
Thanks for your feedback.

2024-02-27 13:45 UTC, Guilhem7 requested changes
Hi, thanks for the modifications, I added some little details to change if possible :)

2024-02-27 13:45 UTC, Guilhem7 commented on arsenal/data/cheats/Web/fuzzer.md
> +feroxbuster --url <URL>
```suggestion
feroxbuster --url <url>
```
We might prefer lowercase for variable name :)

2024-02-27 13:45 UTC, Guilhem7 commented on arsenal/data/cheats/Web/fuzzer.md
> +feroxbuster --url <URL> -w <wordlist>
```suggestion
feroxbuster --url <url> -w <wordlist>
```

2024-02-27 13:45 UTC, Guilhem7 commented on arsenal/data/cheats/Web/fuzzer.md
> +feroxbuster -u <URL> -H Accept:application/json "Authorization: Bearer {token}"
```suggestion
feroxbuster -u <url> -H "<header>" "<header>"
```

2024-02-27 13:45 UTC, Guilhem7 commented on arsenal/data/cheats/Web/fuzzer.md
> +## Multiple headers:
```suggestion
## Multiple headers
```

2024-02-27 13:45 UTC, Guilhem7 commented on arsenal/data/cheats/Web/fuzzer.md
> +feroxbuster -u <URL> --auto-bail
```suggestion
feroxbuster -u <url> --auto-bail
```

2024-02-27 13:45 UTC, Guilhem7 commented on arsenal/data/cheats/Web/fuzzer.md
> +feroxbuster -u http://[::1] --no-recursion -vv
```suggestion
feroxbuster -u <proto|https>://[<ipv6>] --no-recursion -vv
```
Let the user choose the protocol (default https I think), and ipv6

2024-02-27 13:45 UTC, Guilhem7 commented on arsenal/data/cheats/Web/fuzzer.md
> +## IPv6, non-recursive scan with INFO-level logging enabled:
```suggestion
## IPv6, non-recursive scan with INFO-level logging enabled
```

2024-02-29 14:06 UTC, Fastiraz commented
Feroxbuster done, is there anything to edit in weevely file ?

2024-03-01 07:48 UTC, Guilhem7 approved these changes

2024-03-01 07:48 UTC, Guilhem7 commented
Hey,
everything seems good to me, thanks for the modifs and for the PR !

2024-03-01 08:32 UTC, merged